apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-ci
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'mwalterspieler@gmail.com'
    privateKeySecretRef:
      key: ''
      name: letsencrypt-production-ci
    http01: {}
