apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-ci
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'mwalterspieler@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-staging-ci
      key: ''
    http01: {}
